Feature/create exchange class
ElasticSwap/elasticswap-sdk pull request #11
Opened 2021-11-12 16:10 UTC by lrsaturnino

- created exchange class
- updated ERC20 class
- created exchange class tests

2021-11-12 17:53 UTC, 0xean requested changes

2021-11-12 17:53 UTC, 0xean commented on src/exchange/Exchange.js
> +  constructor(sdk, address, baseTokenAddress, quoteTokenAddress) {
would modify `adress` to `exchangeAddress` so its more specific.

2021-11-12 17:53 UTC, 0xean commented on src/exchange/Exchange.js
> +    return this.baseToken.balanceOf(this.ownerAddress);
I think we should refactor `ownerAddress`.  Owner is typically used for the admin of solidity contracts as in `onlyOwner` so this could be userAddress.

I am also concerned with storing this address since the SDK signer could change and we would still have this address being stored as the owner now.  why not just use this._sdk.address?

2021-11-12 17:53 UTC, 0xean commented on src/exchange/Exchange.js
> +    if (!(this.baseTokenBalance) || !(this.quoteTokenBalance)) {
these checks needs to be done against the actual amounts.

IE baseTokenBalance >= baseTokenQtyDesired

2021-11-12 17:53 UTC, 0xean commented on src/exchange/Exchange.js
> +      expirationTimestamp,
we need to check that this timestamp is in the future.

2021-11-12 17:53 UTC, 0xean commented on src/exchange/Exchange.js
> +      baseTokenQtyDesired,
we should check the the *qtyDesired >= *qtyMin

2021-11-12 17:53 UTC, 0xean commented on src/exchange/Exchange.js
> +    if (!(this.baseTokenAllowance) || !(this.quoteTokenAllowance)) {
we need to check that the lp token balance of the caller is >= liquidityTokenQty

2021-11-12 17:53 UTC, 0xean commented on src/exchange/Exchange.js
> +    if (!(this.baseTokenAllowance) || !(this.quoteTokenAllowance)) {
and that they have provided an approval for the lp token, not the quote or base token

2021-11-12 17:53 UTC, 0xean commented on src/exchange/Exchange.js
> +    const exchange = await this.contract;
any reason why we are creating a new contract each time a new call is made?

2021-11-12 17:53 UTC, 0xean commented on src/exchange/Exchange.js
> +    if (!(this.baseTokenBalance)) {
need to check actual balance and approval, they need to be greater than baseTokenQty.

Also baseTokenQty is mispelled, please fix.

2021-11-12 17:53 UTC, 0xean commented on src/exchange/Exchange.js
> +      expirationTimestamp,
check that timestamp is in the future

2021-11-12 17:53 UTC, 0xean commented on src/exchange/Exchange.js
> +      return false;
same as above.

2021-11-12 17:53 UTC, 0xean commented on test/exchange/Exchange.test.mjs
> +import chai from 'chai';
This needs a lot of cleanup, please remove all tests that aren't specifically testing the SDK

2021-11-16 12:38 UTC, 0xean requested changes
👏  this is looking much better, but we still have a few things to fix. 

I left a comment on one item but the other two things we should resolve are.

1. We don't have any tests of the failure states.  For example, we should add a test for each possible way a function call would fail.  So for `swapBaseForQuote` we might add a test where the caller doesn't have enough balance of the base token or enough approval of the base token.  We could test a bad expiration timestamp as well.  This should be done for all failure states in which you are currently returning "false"
2. I think we need to do something besides just returning "false" for these calls.  The user wont understand the reason why its failed and not be able to take any action on it besides guessing.  I would recommend we create a standard set of errors that are thrown for these failures.  They would have strings like `NOT_ENOUGH_BALANCE` `TIMESTAMP_EXPIRED`, etc. If you need an example of this let me know, I think I could find some example code from other projects.

2021-11-16 12:38 UTC, 0xean commented on src/exchange/Exchange.js
> +    if (this.lpTokenAllowance < liquidityTokenQty) {
We need to check their lp token balance here also

2021-11-17 18:00 UTC, lrsaturnino commented
merging to get release in production, further adjustments will be applied on a new branch

2021-11-17 18:00 UTC, merged