Feature/mathlib func#6
ElasticSwap/elasticswap-sdk pull request #14
Opened 2021-11-29 14:47 UTC by smalldutta

Resolves #6 and adds the solidity math lib functions to the sdk as well, 
Testing for all functions (some unit, some integration) is present as well.

2021-11-29 19:30 UTC, 0xean requested changes
Left a few comments in certain sections, let me know if you need help with any of it and we can get this merged!

2021-11-29 19:30 UTC, 0xean commented on src/utils/mathLib.js
> +  _baseTokenQtyDesired,
I know the solidity uses the _varName format for user supplied variables, but the SDK doesn't not anywhere else, so I think we should stick to one format in the sdk and modify these to fit with the rest of the style.

2021-11-29 19:30 UTC, 0xean commented on src/utils/mathLib.js
> +  const inputs = {
maybe am I missing it, but where is this object used?

2021-11-29 19:30 UTC, 0xean commented on src/utils/mathLib.js
> +  const inputs = {
unused

2021-11-29 19:30 UTC, 0xean commented on src/utils/mathLib.js
> +  // doubt: not required as this is a lib?
yea, can be removed.

2021-11-29 19:30 UTC, 0xean commented on src/utils/mathLib.js
> +const internalBalancesBNCleaner = (_internalBalances) => {
would maybe rename this function to something like "....BNConverter"

2021-11-29 19:30 UTC, 0xean commented on src/utils/mathLib.js
> +const BigNumber = require('bignumber.js');
We should stick with the ES6 style imports here and then also rename the file to .mjs after we modify how we export the functions.

I can help if you get stuck here.

2021-11-29 23:08 UTC, smalldutta commented on src/utils/mathLib.js
> +  _baseTokenQtyDesired,
I agree, conflicting styles will just lead to messier code over time, should I then use the JS convention(`varName`) instead of the `_varName`?

2021-12-02 23:33 UTC, 0xean approved these changes

2021-12-02 23:34 UTC, merged